# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Agunicat
tagline:          'agunicat'
description:      'Tales of an eternal apprentice~'
url:              https://blog.agunicat.co
baseurl:          https://blog.agunicat.co/

author:
  name:           'Agunicat'
  url:            https://blog.agunicat.co

urls:
  - text: All Posts
    url: /posts
  - text: Tags
    url: /tags
#- text: XML Feed
#  url: /feed.xml
paginate:         50

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/Crashlaker/agunicat
